title: Product

tabs:
  infos:
    icon: question
    columns:          
      - width: 1/2
        fields:
          types:
            label: Type(s)
            type: checkboxes
            options: query
            query: page.parent.types.split
            width: 1/2
          materials:
            label: Matière(s)
            type: checkboxes
            options: query
            query: page.parent.materials.split
            width: 1/2
          price:
            label: Price
            type: number
            required: true
            min: 100
            width: 1/2
          quantity:
            label: Quantité en stock
            type: number
            required: true
            width: 1/2
      
      - width: 1/1
        fields:
          description:
            label: Description
            type: textarea
  order:
    label: Stock
    icon: cart
    fields:
          orderMode:
            label: Mode de commande
            type: checkboxes
            options:
              stock: Modèles en stock
              order: Production à la commande
            width: 1/2
          options:
            label: Options
            type: structure
            fields:
              name:
                label: Nom
                type: text
              entries:
                label: Options
                type: tags
            width: 1/2
          models:
            label: Modèles
            type: structure
            fields:
              model:
                label: Modèle
                type: text
              quantity:
                label: Quantité
                type: number
              price:
                label: Prix
                type: number
              when:
                orderMode: stock
  gallery:
    label: Galerie
    icon: layers
    sections:
      gallerySection:
        headline: Galerie
        type: files
        layout: cards
        image:
          back: black