title: Product

tabs:
  infos:
    icon: question
    columns:
      - width: 1/2
        fields:
          pictures:
            label: Images
            type: files
            layout: cards
            image:
              back: white
      
      - width: 1/2
        fields:
          description:
            label: Description
            type: textarea
          types:
            label: Type(s)
            type: multiselect
            options: query
            query: page.parent.types.split
            width: 1/2
          materials:
            label: Matière(s)
            type: multiselect
            options: query
            query: page.parent.materials.split
            width: 1/2
          info:
            label: Type ou matière introuvable ?
            type: info
            text: Pour être disponible pour ce produit, une option doit d'abord être renseignées dans l'onglet boutique du site, puis au niveau de son artisan.
  stock:
    label: Commande
    icon: cart
    columns:
      - width: 1/1
        fields:
          price:
            label: Prix
            type: number
            after: €
            width: 1/4
            required: true
          delivery:
            label: Livraison
            type: toggle
            width: 1/4
            help: |
              Délais à définir dans (link: http://localhost:8888/maison-marey/panel/site#shop text: l'onglet maison marey de la racine du panel).
          withdrawal:
            label: Retrait en boutique
            type: toggle
            width: 1/4
      - width: 1/2
        fields:
          order:
            label: Production à la commande
            type: toggle
            default: true
            width: 1/2
          productionTime:
            label: Délai moyen de production
            type: number
            after: jours
            default: 7
            width: 1/2
            when:
              order: true
          options:
            label: Options
            type: structure
            when:
              order: true
            fields:
              name:
                label: Nom
                type: text
              entries:
                label: Options
                type: structure
                fields:
                  name:
                    label: Nom
                    type: text
                  extraCost:
                    label: Surcoût
                    type: number
                    after: €
                    min: 0
                    default: 0
                  extraTime:
                    label: Délai supp.
                    type: number
                    after: jours
                    min: 0
                    default: 0
      - width: 1/2
        fields:
          stock:
            label: Modèles en stock
            type: toggle
            width: 1/2
          withdrawalTime:
            label: Délai de retrait
            type: number
            after: jours
            width: 1/2
            default: 0
            help: Temps éventuellement nécessaire à l'acheminement en boutique.
            when:
              withdrawal: true
          models:
            label: Modèles
            type: structure
            when:
              stock: true
            fields:
              name:
                label: Nom
                type: text
              quantity:
                label: Quantité
                type: number
                width: 1/2
              extraCost:
                label: Surcoût
                type: number
                after: €
                default: 0
                min: 0
                width: 1/2
              cover:
                label: Image
                type: files
                layout: cards
                multiple: false
  gallery:
    label: Galerie
    icon: layers
    sections:
      gallerySection:
        headline: Galerie
        type: files
        layout: cards
        image:
          back: black